### ISSUE TITLE
04 sortCitiesArray

### ISSUE THREAD

**Issue by Kalita-Roman** [OlegYar/js-assignments#11]
https://github.com/OlegYar/js-assignments/blob/99cb26d542037b9354a00def2b36012a11f35a88/task/04-arrays-tasks.js#L507-L524

There is a nicer approach
```
function sortCitiesArray(arr) {
  return arr.sort((a, b) => {
    return a.country.localeCompare(b.country) || a.city.localeCompare(b.city);
  });
}
```

**Comment by OlegYar** [comment]
I understood and rewrote
