### ISSUE TITLE
06 isTriangle

### ISSUE THREAD

**Issue by Kalita-Roman** [OlegYar/js-assignments#17]
https://github.com/OlegYar/js-assignments/blob/3005a8097743c8e4748944d35c283943d718cf6a/task/06-conditions-n-loops-tasks.js#L100-L113
```
function isTriangle(a, b, c) {
  return ((a + b) > c) && ((b + c) > a) && ((a + c) > b);
}
```

**Comment by OlegYar** [comment]
I understood and rewrote
