### ISSUE TITLE
06 doRectanglesOverlap

### ISSUE THREAD

**Issue by Kalita-Roman** [OlegYar/js-assignments#18]
https://github.com/OlegYar/js-assignments/blob/3005a8097743c8e4748944d35c283943d718cf6a/task/06-conditions-n-loops-tasks.js#L148-L196

Try something like that:
```
function doRectanglesOverlap(rect1, rect2) {
  return rect1.top+rect1.height>=rect2.top&&rect1.left+rect1.width>=rect2.left;
}
```

**Comment by OlegYar** [comment]
I understood and rewrote
