### ISSUE TITLE
01 encodeToRot13

### ISSUE THREAD

**Issue by Kalita-Roman** [OlegYar/js-assignments#2]
https://github.com/OlegYar/js-assignments/blob/99cb26d542037b9354a00def2b36012a11f35a88/task/01-strings-tasks.js#L237-L250

Think about using `replace()` method. Put a regexp as 1st argument and a function as a 2nd argument.
```
function encodeToRot13(str) {
  return str.replace( ... , ... );
}
```

**Comment by OlegYar** [comment]
Issue solved

**Comment by OlegYar** [comment]
The issue's solved
