### ISSUE TITLE
06 isBracketsBalanced

### ISSUE THREAD

**Issue by Kalita-Roman** [OlegYar/js-assignments#21]
https://github.com/OlegYar/js-assignments/blob/1b918b5c971886f894ed29c74e3139f206babf26/task/06-conditions-n-loops-tasks.js#L444-L484

I would solved without a stack, but in a `while` loop. For each step replace in the string patterns like `'[]','{}',...`. If string turns to an empty string, then true. If string can't turn to an empty, then false.

**Comment by OlegYar** [comment]
The issue's solved

**Comment by Kalita-Roman** [comment]
👍
