### ISSUE TITLE
06 timespanToHumanString

### ISSUE THREAD

**Issue by Kalita-Roman** [OlegYar/js-assignments#22]
https://github.com/OlegYar/js-assignments/blob/1b918b5c971886f894ed29c74e3139f206babf26/task/06-conditions-n-loops-tasks.js#L532-L536

I would use ternary operator here.
Looks shorter and more readable.
```
...
  } else if (sec > 90 && min <= 45) {
      return min < 2 ? `2 minutes ago` :  `${Math.floor(min)} minutes ago` 
  } else if (min > 45 && min <= 90) {
...
```

**Comment by OlegYar** [comment]
I understood and rewrote. I also used ternary operator in other places, where it's possible
