### ISSUE TITLE
02 getLastDigit

### ISSUE THREAD

**Issue by Kalita-Roman** [OlegYar/js-assignments#4]
https://github.com/OlegYar/js-assignments/blob/99cb26d542037b9354a00def2b36012a11f35a88/task/02-numbers-tasks.js#L130-L133

Think about [this operator %](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder)

**Comment by OlegYar** [comment]
The issue's solved
