### ISSUE TITLE
04 getFalsyValuesCount

### ISSUE THREAD

**Issue by Kalita-Roman** [OlegYar/js-assignments#9]
https://github.com/OlegYar/js-assignments/blob/99cb26d542037b9354a00def2b36012a11f35a88/task/04-arrays-tasks.js#L429-L439

In this situations when you need a variable to accumulate any result of going through an array think about the reduce() method.

BTW, The `forEach()` method is more suitable here. `map` returns new array, and it's expected this array will be used
![image](https://user-images.githubusercontent.com/17515584/104567058-6ae1d900-565f-11eb-8413-e987c62b4a26.png)

**Comment by OlegYar** [comment]
The issue's solved
